name: netwalking_global
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get:
  shared_preferences:
  flutter_screenutil: ^5.9.0
  flutter_svg:
  flutter_spinkit:
  flutter_otp_text_field:
  google_maps_flutter: ^2.12.3
  image_picker: ^1.1.2
  image_cropper:
  web_socket_client:
  web_socket_channel:
  loading_animation_widget: ^1.3.0
  cached_network_image:
  shimmer:
  intl: ^0.20.2
  geocoding: ^2.0.5
  url_launcher: ^6.1.10
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0



flutter:


  uses-material-design: true


  assets:
     - assets/icons/
     - assets/language/
     - assets/image/



fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
